#ifndef __CE_SCORE_WEIGHTS_MQH__
#define __CE_SCORE_WEIGHTS_MQH__

enum CEScoreWeights
{
   // Trend
   SCORE_TREND_STRONG = 30,
   SCORE_TREND_NORMAL = 20,
   SCORE_TREND_WEAK   = 10,

   // Structure
   SCORE_STRUCTURE_STRONG = 20,
   SCORE_STRUCTURE_NORMAL = 10,
   SCORE_STRUCTURE_WEAK   = 0,

   // Momentum
   SCORE_MOMENTUM_STRONG = 10,
   SCORE_MOMENTUM_NORMAL = 5,
   SCORE_MOMENTUM_WEAK   = 0,

   // Liquidity
   SCORE_LIQUIDITY_STRONG = 20,
   SCORE_LIQUIDITY_NORMAL = 10,
   SCORE_LIQUIDITY_WEAK   = 0,

   // Volatility
   SCORE_VOLATILITY_STRONG = 20,
   SCORE_VOLATILITY_NORMAL = 10,
   SCORE_VOLATILITY_WEAK   = 0
};

#endif